displayName=PetScape
author=DamnLol
description=Populate the world with Pets, Fill your house with Pets and even give your Pet some Pets!
tags=pet,boss,bossing,poh,house,skilling,zoo,pets,follower,population,spawn,immersion
plugins=com.DamnLol.PetScape.PetScapePlugin
build=standard
version=2.2.2